### PR TITLE
Added poster for uri attr filtering

### PR DESCRIPTION
**Pull request by adon-at-work**
Introduced in HTML 5, there's a <video poster=""> attribute expecting URL:
https://developer.mozilla.org/en/docs/Web/HTML/Element/video

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by adon-at-work** [comment]
We need to treat data attribute of object tag too. But instead of including data attribute here, I think we need to ban some dangerous tag names such as object when an output placeholder is there.

**Comment by neraliu** [comment]
do u mean that we should ban the "object" tag or some attributes defined in "object" tag?

**Comment by adon-at-work** [comment]
i prefer flagging the developers when output expressions are placed inside <object>, <embed>, <svg>, <comment>, <script> (this is done), <style> (tentatively), etc...

**Comment by neraliu** [comment]
please create the feature request for it.

**Pull request merged**
